### PR TITLE
docs: update `reduce-readme.yml` example

### PR DESCRIPTION
**Pull request by Mo-Gul**
make example a bit more complex to easier find out how to modify it,
if one is new to this topic.

### CODE REVIEW

**Comment by mojavelinux** [comment]
I don't see how this improves the example in any way. All you've done is run it on a file in a different folder. (I will update the version of the checkout action, though).

**Comment by Mo-Gul** [comment]
You are absolutely right, that is all I have done. And this may be trivial to you (being a professional programmer). But for me, as a newbie, never being in touch with GitHub Actions so far, it is hard(er) to find out how it works. For example what is simply a name and what is a path. But for people like me my suggested minor change might help.

Anyway, many thanks for this great package!!

**Comment by mojavelinux** [comment]
Thanks for the appreciation.

The description of path is explained in the GitHub Actions docs. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore It's not the responsibility of this project to teach GitHub Actions concepts. We provide an example of something that will get you started quickly. After that, the GitHub Actions documentation should be your reference.

**Comment by mojavelinux** [comment]
I also want to add that by prefixing the path with the `docs/` folder makes the snippet less useful as a reusable example. A vast majority of people who are interested in this GitHub Actions set up want to use it to rewrite the README for the project (which is not typically in the docs folder). By adding the prefix, we confuse new users by making it something they have to remove. So there's just no good justification for making the example more complicated.

However, if you think that an explanation below the example would help clarify how it is working, then I'd be willing to consider that.

**Comment by Mo-Gul** [comment]
Thank you for adding the comment line

https://github.com/asciidoctor/asciidoctor-reducer/blob/f269faa0a7d98b93cfe04dccd4e5aa218826dc1a/README.adoc?plain=1#L290-L292

As I stated earlier, I am a newbie and thus I trust your decision.

I think one way to not make the example (explanation) over-complicated would be to write before or after the example that it is assumed that the README source and destination (files) are in the `docs` folder. If files would then be in the root folder, the `docs/` part could be removed by a simple search and replace by users, which (I think) is acceptable effort.

But again: It is _your_ repository and _you_ are the expert.

_Many thanks for your time !!_

**Comment by mojavelinux** [comment]
> If files would then be in the root folder, the docs/ part could be removed by a simple search and replace by users, which (I think) is acceptable effort.

I still respectfully disagree. It's not acceptable to introduce complexity for a hello world example like this. If your README is in another folder, then it seems far more reasonable that you would have to be the one to add the prefix.

**Pull request closed without merging**
